[phases.install]
cmds = ["/opt/venv/bin/pip install -r requirements.txt"]

[phases.build]
cmds = [
  "/opt/venv/bin/python manage.py collectstatic --no-input",
  "/opt/venv/bin/python manage.py migrate",
  "echo \"from django.contrib.auth import get_user_model; U=get_user_model(); U.objects.filter(username='admin').exists() or U.objects.create_superuser('admin', '', 'admin1234')\" | /opt/venv/bin/python manage.py shell"
]

[start]
cmd = "/opt/venv/bin/gunicorn TP_208.wsgi:application"
